[package]
name = "dioxus-logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[features]
#stdio = []
#http_logging = ["dep:reqwest"]

[dependencies]
log = { version = "0.4", features = ["std"] }
#reqwest = { version = "0.11", features = [] }
web-sys = { version = "0.3.60", features = ["console"] }
